config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get "search"
    end
  end

  resources :images, only: [:destroy]
  resources :users, only: [:index, :show, :new, :update, :edit] do
    collection do
      get "new1", to: "users#new1"
      get "new2", to: "users#new2"
      get "new3", to: "users#new3"
      get "new4", to: "users#new4"
      get "new5", to: "users#new5"
      get "logout", to: "users#logout"
      get "payment"
      get "identification"
    end
    member do
      get "listing"
      get "profile"
    end
  end
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_ancestry
  has_many :items

  def abc_sort(brand_cat)
    children = brand_cat.children.sort{|a,b| a.name <=> b.name}
    
    topchar = children[0].name[0]
    abclist = []
    common_initial_brands = []
    children.each do |c|
      if c.name[0] == topchar
        common_initial_brands << c
      else
        abclist << [topchar ,common_initial_brands]
        common_initial_brands = []
        # topcharとその配列をセットし直す
        topchar = c.name[0]
        common_initial_brands << c
      end
    end
    return abclist
  end

  def self.search(keyword)
    return Brand.limit(10).order("name") unless keyword
    Brand.where('name LIKE(?)', "#{keyword}%").order("name").limit(10)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items
  def self.get_root_category
    # Category.find(1)
  end
end

app/models/days_to_ship.rb
class DaysToShip < ActiveHash::Base
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  # belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  # belongs_to :brand
  # belongs_to :category
end

app/models/item_status.rb
class ItemStatus < ActiveHash::Base

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

end

app/models/shipping_charger.rb
class ShippingCharger < ActiveHash::Base

end

app/models/shipping_method.rb
class ShippingMethod < ActiveHash::Base
end

app/models/trade_status.rb
class TradeStatus < ActiveHash::Base

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
      if current_user.nickname
        return root_path
      end
      new1_users_path
    else
      root_path
    end
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    
  end


  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @brands = Brand.search(params[:keyword])
  end

  def show
    @brand_cat = Brand.find(params[:id])

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  def index
    @items = Item.all.order("created_at DESC")
    @q = Item.ransack(params[:q])

  end


  def search
    @q = Item.ransack(params[:q])
    @items = @q.result()
    if params[:item] && params[:item][:brand_id]
      @items = @q.result().where(brand_id: params[:item][:brand_id])
    end
    if params[:category_ids]
      @items = @q.result().where(category_id: params[:category_ids])
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      # @item.category.update(items_size: @item.category.items.size)
      if params[:item_images]
        image_params[:image].each do |img|
          @item.images.create(image: img)
        end
      end
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end


  def new
    @item = Item.new
  end

  def show
    
  end

  def create
    @item = Item.create(item_params)
    image_params[:image].each do |img|
      @item.images.create(image: img)
    end
  end

  def  destroy
    if @item.destroy
      # @item.category.update(items_size: @item.category.items.size)
      # redirect_to listing_user_path(current_user.id)
      redirect_to root_path(current_user.id)

    else
      render :edit
    end
  end


  
  private
  def item_params
    params.require(:item).permit(
      :title, :description, :prefecture_id, :shipping_charger_id, :shipping_method_id,
      :days_to_ship_id, :item_status_id, :price
    ).merge( trade_status_id: 1)
  end

  def image_params
    params.require(:item_images).permit(image: [])
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,
  only: [:logout, :payment, :identification, :update, :new1, :show ]


  def new1
    render "users/new/signin1"
  end
  def new2
    render "users/new/signin2"
  end
  def new3
    render "users/new/signin3"
  end
  def new4
    render "users/new/signin4"
  end
  def new5
    render "users/new/signin5"
  end
  
  def new
  end


  def create
    
  end

  def update
    if @user.update(user_params)
      redirect_to new2_users_path
    else
      render :new1
    end
  end
  def identification
  end



  private

  def user_params
    params.require(:user).permit(:nickname, :email,
     :family_name, :first_name, :family_name_kana, :first_name_kana,
     :birth_year, :birth_month, :birth_date)
  end

  def set_user
    @user = User.find(current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<% image_url = (item.images[0]) ? item.images[0].image : '/images/images.jpeg' %>
<li class="card-item">
  <%= link_to "/items/#{item.id}", class: "card-item", method: :get do %>
    <%= image_tag image_url, class: 'hoge', size: '188x188' %>
      <h3 class="A"><%="¥#{item.price}"%></h3>
    <figcaption class="card-text">
      <%= item.description %>
    </figcaption>
  <% end %>
</li>

app/views/items/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/items/edit.html.erb
<div class="new-item">
  <div class="new-item__top">
    <div class="new-item__top__icon">
      <%= link_to root_path do %>
        <img src="https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg" alt="Mercari" class="merukari-icon">
      <% end %>
    </div>
  </div>
  <div class="new-item__main">
    <div class="new-item__main__title">
      商品の情報を編集
    </div>
    <div class="new-item__main__input">
      <%=render partial: 'items/form'%>
    </div>
  </div>
</div>

<style type='text/css'>
.header, .footer-wrapper {
  display: none;
}
</style>
<script>
$(".submit-btn").val("変更する");
$(".submit-btn").attr("data-disable-with","処理中");
$(".return-btn").text("キャンセル");
$(".return-btn").attr("href", "/items/<%=@item.id%>");
$("form.edit_item").prepend(`<input type="hidden" name="_method" value="patch">`);
$('.image_preview_wrap .file_button').text('追加する画像を選択');
</script>

app/views/items/index.html.erb
<style>
#default_header {
  display: none;
}
</style>

<%= render "layouts/header_with_category" %>
<div class="items_index_wrapper">
<div class="top-content-image">
  <div class="top-content-image-picture">
    <div class="right-arrow">
    </div>
    <div class="left-arrow">
    </div>
    <div class="selection-pointer">
    </div>
  </div>
</div>
 <div class="main">
    <div class="cat">
      <h2>人気のカテゴリー</h2>
      <div class="cat__box">
        <ul class="nav">
          <li class="nav-list"><a href="#">レディース</a></li>
          <li class="nav-list"><a href="#">メンズ</a></li>
          <li class="nav-list"><a href="#">家電・スマホ・カメラ</a></li>
          <li class="nav-list"><a href="#">おもちゃ・ホビー・グッズ</a></li>
        </ul>
      </div>
    </div>
  <div class="wrap">
    <div class="women-group">
    <div class="women-group__title">
      <h3 class="group-new">レディース新着アイテム</h3>
      <a href="#">もっと見る 〉</a>
    </div>
    <section class="card-section">
      <ul class="card-list">
        <%= render @items, partial: 'items/item'%>
     </ul>
  </section>
</div>
    <div clas="women-group">
    <div class="women-group__title">
      <h3 class="group-new">レディース新着アイテム</h3>
      <a href="#" class="details">もっと見る ></a>
    </div>
    <section class="card-section">
      <ul class="card-list">
        <% 0.upto(9) do |t|%>
          <li class="card-item">
            <%= image_tag 'images.jpeg', class: 'hoge', size: '188x188' %>
              <h3 class="A">¥1,200</h3>
            <p class="card-text">ワコールセーター</p>
          </li>
        <%end%>
      </ul>
    </section>
  </div>
  </div>
</div>
</div>

app/views/items/show.html.erb
<% image_url = (@item.images.length > 0) ? @item.images[0].image : '/images/images.jpeg' %>
<body class="item_show_wrap">

<%# <%=link_to "to_purchases", purchases_path %> %>
  <div class="l-single-container">
  <div class="l-content">
    <section class="item-box-container">
      <h1 class="item-name"><%=@item.title%></h1>
    
      <div class="item-main-content">
        <div class="item-photo">
          <div class="owl-carousel owl-loaded owl-drag">
            <div class="owl-stage-outer">
              <div class="owl-stage" style="left: 0px; width: 1500px;">
                <div class="owl-item active" style="width: 300px;">
                  <div class="owl-item-inner is-higher-height" id="display_img">
                    <% @item.images.each do |i| %>
                      <%= image_tag i.image, id: "image#{i.id}",
                     class: 'owl-lazy img_displayed hidden', size: '300x300' %>
                    <%end%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="owl-nav disabled">
              <div class="owl-prev">prev</div>
              <div class="owl-next">next</div>
            </div>
            <div class="owl-dots">
             <!--imageを2枚以上投稿すると表示される-->
              <div class="owl-dot active"><span></span>
                <div class="owl-dot-inner" id="select_img">
                  <% @item.images.each do |i|%>
                    <%= image_tag i.image, class: "is-higher-height", size: "60x60", "data-image-id": i.id %>
                  <%end%>
                <!--<img src="https://static.mercdn.net/item/detail/orig/photos/m72019720622_1.jpg?1574782868" class="is-higher-height" width="60" height="60">-->
                </div>
              </div>
            </div>
            <script>
              $($("#display_img img")[0]).removeClass("hidden");
              $("#select_img img").on("click", function () {
                let imageId= $(this).data("image-id");
                
                $("#display_img img").addClass("hidden");
                $(`#display_img #image${imageId}`).removeClass("hidden");
              })
            </script>
          </div>
          <table class="item-detail-table">
            <tbody>
              <tr>
                <th>出品者</th>
                <td>
                  <%# <%= link_to "#{@item.user.nickname}", "#" %> %>
                  <div>
                    <div class="item-user-ratings-good">
                      <i class="fas fa-laugh"></i>
                      <span>471</span>
                    </div>
                    <div class="item-user-ratings">
                      <i class="fas fa-meh"></i>
                      <span>7</span>
                    </div>
                    <div class="item-user-ratings">
                      <i class="fas fa-frown"></i>
                      <span>1</span>
                    </div>
                  </div>
                </td>
              </tr>
              <tr>
                <th>カテゴリー</th>
                <td>              
                  <div>
                    <%# <%= link_to @item.category.parent.parent.name if @item.category.parent.parent%> %>
                  </div>
                  <a href="https://www.mercari.com/jp/category/36/">
                    <div class="item-detail-table-sub-category">
                      <i class="fa fa-angle-right"></i> 
                      <%# <%= link_to @item.category.parent.name %> %>
                    </div>
                  </a>
                  <a href="https://www.mercari.com/jp/category/371/">
                    <div class="item-detail-table-sub-sub-category">
                      <i class="fa fa-angle-right"></i> 
                      <%# <%= link_to @item.category.name, category_path(@item.category.id) %> %>
                    </div>
                  </a>
                </td>
              </tr>
              <tr>
                <th>ブランド</th>
                <td>          
                  <div>
                    <%# <%= link_to @item.brand.name, "/brands/#{@item.brand.id}" %> %>
                  </div>
                </td>
              </tr>
              <tr>
                <th>商品の状態</th>
                <%# <td><%= @item.item_status.name %></td> %>
              </tr>
              <tr>
                <th>配送料の負担</th>
                <%# <td><%= @item.shipping_charger.name %></td> %>
              </tr>
              <tr>
                <th>配送の方法</th>
                <%# <td><%= @item.shipping_method.name %></td> %>
              </tr>
              <tr>
                <th>配送元地域</th>
                <td>
                  <%# <%= link_to "#{@item.prefecture.name}", "#" %> %>
                </td>
              </tr>
              <tr>
                <th>発送日の目安</th>
                <%# <td><%= @item.days_to_ship.name %></td> %>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="item-price-box">
          <span class="item-price bold"><%= "¥#{@item.price}" %></span>
          <span class="item-tax">（税込）</span>
          <%# <% if @item.shipping_charger.id == 1 %> %>
            <span class="item-shipping-fee">送料込み</span>
          <%# <% else %> %>
            <span class="item-shipping-fee">着払い</span>
          <%# <% end %> %>
        </div>
        <%# <% if user_signed_in? && current_user.id != @item.user_id %> %>
          <a class="item-buy-btn" href="">
            購入画面に進む
          </a>
        <%# <%end%>          %>
        <div class="item-description">
          <p class="item-description-inner">
            <%= @item.description %>
          </p>
          <%# <%= link_to "##{@item.brand.name}", brand_path(@item.brand.id) %> %>
          <%# <%= link_to "##{@item.category.name}" %> %>
        </div>
        <%# <% if user_signed_in? && current_user.id != @item.user_id %> %>
          <div class="item-button-container">
            <div class="item-button-left">
              <a href="" class="item-button item-button-like">
                <i class="far fa-heart"></i>
                <span>いいね!</span>
                <span data-num="like">1</span>
              </a>
              <a href="" class="item-button item-button-report clearfix">
                <i class="far fa-flag"></i>
                <span>不適切な商品の報告</span>
              </a>
            </div>
            <div class="item-button-right">
              <a href="" target="_blank">
                <i class="fas fa-lock"></i>
                <span>あんしん・あんぜんへの取り組み</span>
              </a>
            </div>
           </div>
        <%# <% end %> %>
      </section>
  
    <%# <% if user_signed_in? && current_user.id == @item.user_id %> %>
      <div class="contents-row">
        <div class="contents-row__container">
          <%= link_to '商品の編集', "/items/#{@item.id}/edit", class: "link_to_edit-btn", method: :get %> 
          <h4 class="text-danger">
          <p class="text-center">or</p>
          <%= link_to 'この商品を削除する', "/items/#{@item.id}", class: "delete-btn", method: :delete, data:
          { confirm: '本当に削除しますか?',
            cancel: 'やめる',
            commit: '削除する'}, title: '削除確認' %>
          </h4>   
        </div>
      </div>
    <%# <% end %> %>

    <div class="comment-form">
      <div class="comment-form__container">
        <div class="attention">相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。</div>
        <form method="post" action="sample.cgi">
          <textarea name="kansou" class="textarea-default"></textarea>
          <input type="submit" value="コメントする">
        </form>
      </div>
    </div>
   </div>
  </div> 
  <div class="breadcrumbs-bottom">
    <% breadcrumb :items %>
    <%# <%= breadcrumbs sseparator: "  &nbsp;&nbsp;&#12297;&nbsp;  "%> %>
  </div>
</body>

app/views/users/_left_nav.html.erb
<div class="left-nav">
      <ul>
        <%= link_to user_path(@user.id) do%>
          <li id="li_mypage"><span>マイページ</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%end%>
        <li><span>やることリスト</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>いいね！一覧</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>出品する</span><span><i class="fas fa-chevron-right"></i></span></li>

        <%# <% if user.items.length > 0%> %>
        <%# <%=link_to listing_user_path(user.id) do%> %>
          <li><span>出品した商品 - 出品中</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%# <%end%> %>
        <%# <%end%> %>
        
        <li><span>出品した商品 - 取引中</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>出品した商品 - 売却済み</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>購入した商品 - 取引中</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>購入した商品 - 過去の取引</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>ニュース一覧</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>評価一覧</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>ガイド</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>お問い合わせ</span><span><i class="fas fa-chevron-right"></i></span></li>
      </ul>
      <h3>メルペイ</h3>
      <ul>
        <li><span>売上・振込申請</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>ポイント</span><span><i class="fas fa-chevron-right"></i></span></li>
      </ul>
      <h3>設定</h3>
      <ul>
        <%# <%=link_to profile_user_path(user.id) do%> %>
          <li id="user_profile"><span>プロフィール</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%# <% end %> %>
        <li><span>発送元・お届け先住所変更</span><span><i class="fas fa-chevron-right"></i></span></li>
          
        <%# <%=link_to payment_users_path do%> %>
          <li id="user_payment"><span>支払い方法</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%# <%end%> %>
        <li><span>メール/パスワード</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%# <%=link_to identification_users_path do%> %>
          <li id="user_identification"><span>本人情報</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%# <%end%> %>
        <li><span>電話番号の確認</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%=link_to logout_users_path do%>
          <li id="user_logout"><span>ログアウト</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%end%>
      </ul>
    </div>
   </div>
  </div>

app/views/users/listing.html.erb
<%= render "layouts/header" %>

<% breadcrumb :listing %>
  <%= breadcrumbs separator: " &rsaquo; "%>

<div class="contents-wrapper">
  <div class="contents clearfix">
    <div class="right-content">   
      <div class="listings">
        <ul class="listing-items">
          出品した商品 
        </ul> 
        <ul class="listing-tabs">
          <li class="active"><a href=""><h3>出品中</h3></a></li>
          <li class=""><a href=""><h3>取引中</h3></a></li>
          <li class=""><a href=""><h3>売却済み</h3></a></li>
        </ul>
        <%current_user.items.each do |i|%>
          <ul class="listing-lists"> 
            <%=link_to item_path(i.id) do%>
              <li class="clearfix"> 
                <% image_url = (i.images.size > 0) ? i.images[0].image : '/images/no_image.png' %>
                <%= image_tag image_url, class: 'listing-item', size: '48x48' %>
                <div class="listing-item-body">
                  <p class="item-title"><%=i.title%></p>
                </div>
                <p><i class="fas fa-chevron-right"></i></p>
              </li>
            <%end%> 
          </ul> 
        <%end%> 
      </div>
    </div>
    
    <div class="left-nav">
      <ul>
        <%= link_to user_path do%>
          <li><span>マイページ</span><span><i class="fas fa-chevron-right"></i></span></li>
        <% end %>  
        <li><span>やることリスト</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>いいね！一覧</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>出品する</span><span><i class="fas fa-chevron-right"></i></span></li>

        <%=link_to listing_user_path do%>
          <li id="user_listing"><span>出品した商品 - 出品中</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%end%>
        
        <li><span>出品した商品 - 取引中</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>出品した商品 - 売却済み</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>購入した商品 - 取引中</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>購入した商品 - 過去の取引</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>ニュース一覧</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>評価一覧</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>ガイド</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>お問い合わせ</span><span><i class="fas fa-chevron-right"></i></span></li>
      </ul>
      <h3>メルペイ</h3>
      <ul>
        <li><span>売上・振込申請</span><span><i class="fas fa-chevron-right"></i></span></li>
        <li><span>ポイント</span><span><i class="fas fa-chevron-right"></i></span></li>
      </ul>
      <h3>設定</h3>
      <ul>
        <%=link_to profile_user_path do%>
          <li id="user_profile"><span>プロフィール</span><span><i class="fas fa-chevron-right"></i></span></li>
        <% end %>
        <li><span>発送元・お届け先住所変更</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%=link_to payment_users_path do%>
          <li id="user_payment"><span>支払い方法</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%end%>
        <li><span>メール/パスワード</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%=link_to identification_users_path do%>
          <li id="user_identification"><span>本人情報</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%end%>
        <li><span>電話番号の確認</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%=link_to logout_users_path do%>
          <li id="user_logout"><span>ログアウト</span><span><i class="fas fa-chevron-right"></i></span></li>
        <%end%>
      </ul>
    </div> 
  </div>
</div>

<%= render "layouts/footer" %>

<script>
$(function () {
  $('#user_listing').addClass('active_nav')
})
</script>

app/views/users/new/_ufooter.html.erb
<footer class="user_new_footer">
  <div class="foot_wrap">
    <ul>
      <li><a href="">プライバシーポリシー</a></li>
      <li><a href="">メルカリ利用規約</a></li>
      <li><a href="">特定商取引に関する表記</a></li>
    </ul>
    <a href="">
      <img src="/images/logo-gray-user-new.svg" alt="logo-gray" width="80" height="65">
    </a>
    <p>©️ 2019 Mercari</p>
  </div>
</footer>

app/views/users/new/signin1.html.erb
<header class="user_new user_new1">
  <%=render partial: "users/new/uheader"%>
</header>
<div class="contents_wrapper1">
  <section class="l-single-container">
    <h3>会員情報入力</h3>
    <%= form_for @user, url: user_path(@user.id), method:"patch" do |f| %>
    <div class="form__inputs">
      <p>ニックネーム<span class="white_in_red">必須</span></p>
      <%=f.text_field :nickname, class: "group1", placeholder: "例）メルカリ太郎" %>
      <p>メールアドレス<span class="white_in_red">必須</span></p>
      <%=f.text_field :email, class: "group1", placeholder: "PC・携帯どちらでも可" %>

  <div class=form-group>
    <h4>本人確認</h4>
    <p class=text>安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。</p>
    <p>お名前(全角)<span class="white_in_red">必須</span></p>
    <div style="display:inline-flex">
      <%=f.text_field :family_name, class: "group2", placeholder: "例）山田"%>
      <%=f.text_field :first_name, class: "group2", placeholder: "例）彩"%>
    </div>
    <p>お名前カナ(全角)<span class="white_in_red">必須</span></p>
    <div style="display:inline-flex">
      <%=f.text_field :family_name_kana,class:"group2",placeholder:"例）ヤマダ"%>
      <%=f.text_field :first_name_kana, class:"group2", placeholder:"例）アヤ"%>
    </div>
    <div class=form-group>
      <p>生年月日<span class="white_in_red">必須</span></p>
    <br>
      <div class="birthday-select-wrap">
        <div class="select-wrap">
          <div style="display:inline-flex">
            <%=f.select :birth_year, (1900..2030).to_a.collect{|y| [y,y]}.unshift(["--",""])%>
              <span id="date">年</span>
            <%=f.select :birth_month, (1..12).to_a.collect{|m| [m,m]}.unshift(["--",""])%>
              </select><span id="date">月</span>
            <%=f.select :birth_date, (1..31).to_a.collect{|d| [d,d]}.unshift(["--",""])%>
              </select><span id="date">日</span>
          </div>
          <div class=form-group>
            <p class=form-info>※ 本人情報は正しく入力してください｡会員登録後､修正するにはお時間を頂く場合があります｡</p>
          <div class=form-group>

          <div class="rc-anchor-center-container">
            <label class="rc-anchor-center-item rc-anchor-checkbox-label" aria-hidden="true" role="presentation" id="recaptcha-anchor-label">
              <span aria-live="polite" aria-labelledby="recaptcha-accessible-status"></span>私はロボットではありません
            </label>
          </div>
        <div class=form-group>
          <p class=text>「次へ進む」のボタンを押すことにより、<a href="#" >利用規約</a>に同意したものとみなします</p>
          <%=f.submit "情報を登録して、次へ進む", class:"button white_in_red"%>

          <%=link_to new2_users_path do%>
          <button type="button" class="white_in_red">登録せず、次へ進む</button>
          <%end%>
        </div>
      <div class=form-group__text-right>
        <p class=text-right><a href="#">本人情報の登録について></a></p>
      </div>
    <%end%>
  </section>
</div>
<%= render partial: "users/new/ufooter" %>